services:
  - type: web
    name: portfolio
    env: static
    buildCommand: hugo --gc --minify
    staticPublishPath: ./public
    envVars:
      - key: HUGO_VERSION
        value: 0.136.5
      - key: HUGO_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 